package com.example.demo.Security.Secure;

import com.example.demo.Entity.Role;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Null;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@AllArgsConstructor
@Data
@Builder
public class SignUp {
    @NotNull(message = " id generated by spring security")
    private String userID;

    @NotNull(message = "email cannot be null")
    private String email;

    @NotNull
    private String password;
    @NotNull
    private Role role;
}
